### ISSUE TITLE
xml2cpp produces invalid output

### ISSUE THREAD

**Issue by H5117** [dbus-cxx/dbus-cxx#12]
Take this XML:
```
<?xml version="1.0" encoding="UTF-8" ?>
<node cppname="some.name">
    <interface name="some.interface">
        <method name="some.method">
            <arg type="a{ss}" name="map" direction="out"/>
        </method>
    </interface>
</node>
```
Make an adapter:
```
[~]$ dbus-cxx-xml2cpp --adapter -f -x example.xml
```
Get the adaptee's method:
```
<...>
virtual std::vector<std::pair<><std::stringstd::string>> some.method( ) = 0;
<...>
```

**Comment by rm5248** [comment]
Unfortunately, this isn't really fixable with the current design, at least not without a fair amount of rework.  Some of the more complicated DBus types don't map easily back to C++ types, so this is one of those instances where you can't use the output of dbus-cxx-xml2cpp directly, but you must use it as a starting point for your code.

**Comment by H5117** [comment]
I see a problem only with VARIANT. I think you have to implement a custom C++ class for it. Other types can be easily represented with C++ types:
```
DBus           C++
-------------------------------
BYTE        <-> uint8_t
BOOLEAN     <-> bool
INT16       <-> int16_t
UINT16      <-> uint16_t
INT32       <-> int32_t
UINT32      <-> uint32_t
INT64       <-> int64_t
UINT64      <-> uint64_t
DOUBLE      <-> double
STRING      <-> std::string
OBJECT_PATH <-> std::string
SIGNATURE   <-> std::string
UNIX_FD     <-> uint32_t
STRUCT      <-> struct {}
ARRAY       <-> std::vector<>
DICT_ENTRY  <-> std::map<>
```
So the main problem is to parse a "type" field correctly, I suppose.

**Comment by rm5248** [comment]
Technically, the problem is because of the templates - because the type that the library properly returns is e.g. `std::map<>` and not `std::map<`, and then you need to fill in what is in the template.  This is complicated by the fact that a map will have two templates, while a vector will have only one.  So the parsing code needs to be smart enough to know that the type is both a templated type, and when it is done with the templated type.

Long-term as well, the `struct` type will be probably be a `std::tuple`, since that provides a templated struct which should interact well with the rest of the library templates, and the variant will be a `std::variant`.

**Comment by rm5248** [comment]
This works correctly now on the dbus-cxx-2 branch; this will not be backported to the current release as it depends on a new API.
