### ISSUE TITLE
Assertion failed in `void DBus::Demarshaling::is_valid(uint32_t)`

### ISSUE THREAD

**Issue by giovasini** [dbus-cxx/dbus-cxx#128]
Hi, 
I am trying to use dbus-cxx to create a Wi-Fi Direct connection.
I found a very similar issue (#105) that was resolved, but it doesn't seem to cover my case.
I am trying to get the value of the `Capabilities` property from the System Bus `fi.w1.wpa_supplicant1.Interface` interface.
I generated a proxy using the `dbus-cxx-xml2cpp` tool.

The program crashes with the following error:
```
wifi_direct_manager: /home/user/github/dbus-cpp/dbus-cxx-2.4.0/dbus-cxx/demarshaling.cpp:309: void DBus::Demarshaling::is_valid(uint32_t): Assertion `( m_priv->m_dataPos + bytesWanted ) <= m_priv->m_dataLen' failed.
```
when I run
```C++
map<basic_string<char>, Variant> capabilities = wpa_supplicant_interface->m_property_Capabilities->value();
```
`m_property_Capabilities` is of type `shared_ptr<PropertyProxy<map<basic_string<char>, Variant>>>`

The property should return a `Dict of {String, Variant}` with a content like
```
{'AuthAlg': ['open', 'shared', 'leap'],
 'Group': ['ccmp-256', 'gcmp-256', 'ccmp', 'gcmp', 'tkip', 'wep104', 'wep40'],
 'GroupMgmt': ['aes-128-cmac', 'bip-gmac-128', 'bip-gmac-256', 'bip-cmac-256'],
 'KeyMgmt': ['none',
             'ieee8021x',
             'wpa-eap',
             'wpa-ft-eap',
             'wpa-eap-sha256',
             'wpa-psk',
             'wpa-ft-psk',
             'wpa-psk-sha256',
             'wps'],
 'MaxScanSSID': 4,
 'Modes': ['infrastructure', 'ad-hoc', 'ap', 'p2p'],
 'Pairwise': ['ccmp-256', 'gcmp-256', 'ccmp', 'gcmp', 'tkip'],
 'Protocol': ['rsn', 'wpa'],
 'Scan': ['active', 'passive', 'ssid']}
```

I am using the latest version 2.4.0 on Ubuntu 22.04.3 LTS.

**Comment by rm5248** [comment]
If possible, can you use dbus-monitor to dump a PCAP file of the bad message?  That will make it easier for me to reproduce and test for.

**Comment by giovasini** [comment]
[dbus-monitor-output.zip](https://github.com/dbus-cxx/dbus-cxx/files/13676878/dbus-monitor-output.zip)
Here is the requested file.
The property request response frame should be No. 146 and it appears to contain the correct data.

**Comment by rm5248** [comment]
Thanks, I can clearly reproduce this now.  It almost appears as though the message is badly formatted, but I'm not positive at the moment.  I'll need to do some investigation in order to confirm.

**Comment by rm5248** [comment]
Good news: I did fix some bugs with handling variants, so the message is now parsed without crashing.

The bad news: Because of how the variants are stored internally, you can't actually _use_ the variant at the moment.

The problem comes down to how variants are stored internally: when you set a variant to a value, it serializes the variant internally and then when you access the value, it deserializes it.  Because we have a fairly complex type that we need to store, the deserialization then fails.  The reason it is done this way is because of how templates work in C++, so if we're extracting into a vector or a map we need to do this in the header file.

I may need to come up with a new scheme of how to internally store the variant data, but if so that may mean an ABI breakage(which is not desirable).

**Comment by rm5248** [comment]
After thinking about it for a bit, I did manage to get it to pass the parsing.  It's rather ugly, but really all of the variant stuff is, so I don't think there's any getting around it.

If you're able to test the [issue-128 branch](https://github.com/dbus-cxx/dbus-cxx/tree/issue-128) out, I would appreciate it.

**Comment by giovasini** [comment]
Great! Now it works. Thanks a lot!
