### ISSUE TITLE
Continious Wifi scanning via WpaSupplicant results in exception because of max_match_rules_per_connection limit

### ISSUE THREAD

**Issue by marfrde** [dbus-cxx/dbus-cxx#144]
I have a problem using dbus to communicate with WpaSupplicant. I don't know if this is a problem with my usage of the lib or if something else is messing with me.
After getting the interface and registering the callback for the ScanDone signal, the scan is started.
In the callback method I read the found ssids and add them to an empty QList to show them later in the UI. Some Seconds later, the scanning is started again.

This loop works for some time without problems. Except that after a handful of scans, the listing of SSIDs produces the following exception:

> Connection ":1.15" is not allowed to add more match rules (increase limits in configuration file if required; max_match_rules_per_connection=512)

One interesting information: It depends on the number of returned ssids. When I get few ssids, it takes more scan cycles to get this error in contrast to an office setting with ~40 ssids where it only takes ~5 scans to trigger this.
The relevant definitions are as following:

```
constexpr auto WpaSupplicantInterfaceInterface = "fi.w1.wpa_supplicant1.Interface";
...
m_methodScan = this->create_method<void(std::map<std::string, ::DBus::Variant>)>(WpaSupplicantInterfaceInterface, "Scan");
m_signalScanDone = this->create_signal<void(bool)>(WpaSupplicantInterfaceInterface, "ScanDone");
...
m_propertyBSSs = this->create_property<std::vector<::DBus::Path>>(WpaSupplicantInterfaceInterface, "BSSs");
...

std::vector<::DBus::Path> GetBSSs()
{
	return m_propertyBSSs->value();
}

```

Is there something wrong with my understandig of DBus or how the library works or is there somthing on a different layer that I just don't see?

Thanks in advance already.

**Comment by rm5248** [comment]
This sounds like a resource leak someplace.  My guess is that you're continually calling the following line, either directly or indirectly:
```
m_signalScanDone = this->create_signal<void(bool)>(WpaSupplicantInterfaceInterface, "ScanDone");
```
It's also possible that while you are creating/destroying objects fine, the library is not internally cleaning up correctly.

Without seeing all of your code I can't be sure.  Could you provide a minimal complete example that shows the behavior?

**Comment by rm5248** [comment]
Thanks, I'll try to take a look at it this week.

If you want to try and debug a big more, you can try turning on the debug logs and seeing the messages that go back and forth.  I suspect that you may see [this method](https://github.com/dbus-cxx/dbus-cxx/blob/f51504cd642e8479681787558797341e86586641/dbus-cxx/connection.cpp#L302) being called a lot.

**Comment by marfrde** [comment]
You are correct, there are many calls to AddMatch. The Error message is here: https://github.com/marfrde/wifiSample/blob/master/debug.log#L10793 after 1026 found occurrences of "AddMatch". Two per AddMatch request and we get to one request to much for the 512 limit mentioned in the original error message.

Is there a way to change the behavior to not fall into that issue or change the code on my side?

**Comment by marfrde** [comment]
Good to know that the log and sample code helped.
Can you please keep an eye open for the missing last 3 characters of the ssid when you search for the other issue?

**Comment by rm5248** [comment]
I don't have a good way to test the sample unfortunately(my wifi adapter does not want to connect to my VM).

Could you try it on your system with two things:

1. set the logging level to trace
2. Take a pcap of the dbus when this happens(`dbus-monitor --pcap`)

I should only need a few seconds of the logs, so you don't need to let it run until it crashes.

There's nothing obvious to me in the code at least, so I'm somewhat mystified as to where this is coming in.

**Comment by rm5248** [comment]
The log does have some very interesting things at the end though:
```
0x84F3E180 DBus.priv.SendmsgTransport [DEBUG] - Have 32 bytes of control after real reading(/var/lib/jenkins/workspace/buildroot_v2.28.1-dev/build/kbg7z_defconfig/buildroot-2023.02/output/build/dbus-cxx-2.3.1/dbus-cxx/sendmsgtransport.cpp:418)
0x84F3E180 DBus.Message [DEBUG] - Message has 0 fds(/var/lib/jenkins/workspace/buildroot_v2.28.1-dev/build/kbg7z_defconfig/buildroot-2023.02/output/build/dbus-cxx-2.3.1/dbus-cxx/message.cpp:342)
0x84F3E180 DBus.Connection [DEBUG] - Got incoming DBus::Message = [ErrorMessage
  Message length: 150
  Endianess: Little
  Serial: 516
  Headers:
    Error Name: org.freedesktop.DBus.Error.LimitsExceeded
    Reply Serial: 646
    Destination: :1.11
    Sender: org.freedesktop.DBus
    Signature: DBus::Signature[s]
](/var/lib/jenkins/workspace/buildroot_v2.28.1-dev/build/kbg7z_defconfig/buildroot-2023.02/output/build/dbus-cxx-2.3.1/dbus-cxx/connection.cpp:447)
BSS receiving failed with exception Connection ":1.11" is not allowed to add more match rules (increase limits in configuration file if required; max_match_rules_per_connection=512)
0x84F3E180 DBus.Connection [DEBUG] - Try to read a message(/var/lib/jenkins/workspace/buildroot_v2.28.1-dev/build/kbg7z_defconfig/buildroot-2023.02/output/build/dbus-cxx-2.3.1/dbus-cxx/connection.cpp:593)
0x84F3E180 DBus.priv.SendmsgTransport [DEBUG] - Have 32 bytes of control after real reading(/var/lib/jenkins/workspace/buildroot_v2.28.1-dev/build/kbg7z_defconfig/buildroot-2023.02/output/build/dbus-cxx-2.3.1/dbus-cxx/sendmsgtransport.cpp:418)
0x84F3E180 DBus.Message [DEBUG] - Message has 0 fds(/var/lib/jenkins/workspace/buildroot_v2.28.1-dev/build/kbg7z_defconfig/buildroot-2023.02/output/build/dbus-cxx-2.3.1/dbus-cxx/message.cpp:342)
0x84F3E180 DBus.signal_proxy [DEBUG] - DBus::signal_proxy<void (NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE,St3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN4DBus7VariantESt4lessIS5_ESaISt4pairIKS5_S7_EEE,St6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE)>::on_dbus_incoming method=PropertiesChanged(/var/lib/jenkins/workspace/buildroot_v2.28.1-dev/build/kbg7z_defconfig/buildroot-2023.02/output/build/dbus-cxx-2.3.1/dbus-cxx/signalproxy.h:97)
0x84F3E180 DBus.signal_proxy [DEBUG] - DBus::signal_proxy<void (NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE,St3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN4DBus7VariantESt4lessIS5_ESaISt4pairIKS5_S7_EEE,St6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE)>::on_dbus_incoming method=PropertiesChanged(/var/lib/jenkins/workspace/buildroot_v2.28.1-dev/build/kbg7z_defconfig/buildroot-2023.02/output/build/dbus-cxx-2.3.1/dbus-cxx/signalproxy.h:97)
0x84F3E180 DBus.signal_proxy [DEBUG] - DBus::signal_proxy<void (NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE,St3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN4DBus7VariantESt4lessIS5_ESaISt4pairIKS5_S7_EEE,St6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE)>::on_dbus_incoming method=PropertiesChanged(/var/lib/jenkins/workspace/buildroot_v2.28.1-dev/build/kbg7z_defconfig/buildroot-2023.02/output/build/dbus-cxx-2.3.1/dbus-cxx/signalproxy.h:97)
0x84F3E180 DBus.signal_proxy [DEBUG] - DBus::signal_proxy<void (NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE,St3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN4DBus7VariantESt4lessIS5_ESaISt4pairIKS5_S7_EEE,St6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE)>::on_dbus_incoming method=PropertiesChanged(/var/lib/jenkins/workspace/buildroot_v2.28.1-dev/build/kbg7z_defconfig/buildroot-2023.02/output/build/dbus-cxx-2.3.1/dbus-cxx/signalproxy.h:97)
^^ This line repeats a bunch of times
```
It seems that the messages are getting stuck for some reason and they're all coming through once the exception is thrown.

**Comment by rm5248** [comment]
I wonder if the problem may be around here: https://github.com/marfrde/wifiSample/blob/95ddd093eb6e0e4280bc775d217af0392d2f9cef/WifiScan.cpp#L27

I'm not sure why the signal keeps getting added, but I'm leaning towards a threading issue at the moment.  It looks like thread 0x85318020 is the main thread(at the start), but in the entire log there are only 72 messages from this thread, while thread 0x84F3E180 appears 6006 times in the log.

Or perhaps it is because a new object is created here: https://github.com/marfrde/wifiSample/blob/95ddd093eb6e0e4280bc775d217af0392d2f9cef/WpaSupplicant/WpaSupplicantDBusClient.cpp#L214

Perhaps the objects are not being deleted and/or the signal is not being removed?

**Comment by marfrde** [comment]
I used "dbus-monitor --system --pcap" because we don't have per-Session connections on that system.
It's available at https://github.com/marfrde/wifiSample/blob/master/logs/capture.pcap

The trace output is here: https://github.com/marfrde/wifiSample/blob/master/logs/trace.log

and the console output for the overview what happened is here: https://github.com/marfrde/wifiSample/blob/master/logs/execution.log

Can you tell me what I can do to help you verify or refute your last guesses?

**Comment by rm5248** [comment]
Thanks for the dumps.

I don't have too much time to look at it closely today, but it does look like there are at least two problems here:

1. dbus-cxx will let you add multiple identical signal matches.  I'm assuming that the dbus-daemon does not check the matches to see if they are logically the same or not.
2. Your code is continually making new objects that are not being destroyed.  Whenever a new proxy object is created, dbus-cxx is currently adding a bunch of matches(that it probably has already added), and then the object is caching the current values of all of the properties from the remote object.

I'm making a few assumptions on point 2 here, mostly because I don't see any `RemoveMatch` calls that would indicate that objects are being destroyed.

I should be able to fix the first issue pretty easily, but you'll probably have to do a bit of work on the second in order to figure out why you seem to be creating so many objects.  Consider using the classes generated from the `dbus-cxx-xml2cpp` program.

**Comment by rm5248** [comment]
After further investigation, point 1 was implemented but it did have a bug where it was checking to see if it it had added the signal match before, but then added it anyway no matter what.  This should be fixed in this branch now: https://github.com/dbus-cxx/dbus-cxx/tree/issue-144

That should at least help you run for longer, but I'm pretty sure there's still an issue with you allocating too many objects when you don't need to.

**Comment by rm5248** [comment]
This should be fixed in latest master; if you are able to test with your code your help would be appreciated
