### ISSUE TITLE
Provide a conan package.

### ISSUE THREAD

**Issue by azubieta** [dbus-cxx/dbus-cxx#4]
Conan (https://conan.io/) would be a great way of distributing the very latest version of this library to the users without having to wait for distribution packagers to do it.

Would you mind to create a Conan package for it?

I'm just a newbie to Conan but I've made one or two packages recipes, but let me know if I can help.

**Comment by rm5248** [comment]
Since I've never used conan before(or have plans to use it in the future), this is not something that I would be interested in creating.  If you want to create a conan build, I'll merge that in.

The packaging that I'm concerned about is for Debian and Debian derivatives, so that is kept up to date(and is how it is built on Jenkins: https://jenkins.rm5248.com/view/dbus-cxx/job/dbus-cxx-stretch/)
