### ISSUE TITLE
Challenges with DBus::Variant

### ISSUE THREAD

**Issue by burns97** [dbus-cxx/dbus-cxx#55]
I'm looking for some guidance on whether I can use dbus-cxx for communicating with wpa_supplicant. I've made some decent progress but running into some challenges using the DBus::Variant.  I saw in another closed issue that to support a{sv} we should use a std:map. Based on that short tid-bit there it sounds like it would work for cases where all the Variant types are the same.  Does it also support cases like P2PDevice.GroupAdd where the types are mixed. 
https://w1.fi/wpa_supplicant/devel/dbus.html#dbus_p2pdevice

If so, I'd love some example code to get me going.  I seem to be spinning my wheels a bit on this one.

**Comment by rm5248** [comment]
> Based on that short tid-bit there it sounds like it would work for cases where all the Variant types are the same. 

Yes; the current master(referred to as dbus-cxx-1.0, library version 0.XX.YY) has variants that templated, and thus must be the same type, e.g. `DBus::Variant<uint32_t>`

> Does it also support cases like P2PDevice.GroupAdd where the types are mixed.
> https://w1.fi/wpa_supplicant/devel/dbus.html#dbus_p2pdevice

The current version in master doesn't support this in an easy way.  You can probably get it to work if you define a custom type, but this can be difficult to get right.  See [this mailing list](https://groups.google.com/forum/#!topic/dbus-cxx/AxLXh8AyIj0) topic for some discussion, and the examples in the [examples/](https://github.com/dbus-cxx/dbus-cxx/tree/master/examples/basics/types) directory.

If you want to try some bleeding-edge stuff that solves many of these problems, checkout the [dbus-cxx-2](https://github.com/dbus-cxx/dbus-cxx/tree/dbus-cxx-2) branch.  I would currently classify this branch as an alpha-release, so while no major changes should happen there is a distinct possibility that things will break in the near future.  dbus-cxx-xml2cpp should also work much better in this branch, so you should be able to auto-generate the correct proxy class to talk with wpa_supplicant.

> If so, I'd love some example code to get me going. I seem to be spinning my wheels a bit on this one.

If you're using wpa_supplicant, something like the following should work.  Note that there's no boilerplate, you can only put in a single variant into the map(since it's templated), and I haven't actually tested this, so it may not compile.
```
std::shared_ptr<DBus::ObjectProxy> proxy = conn->create_object_proxy( "wpa.supplicant.dbus.name", "/wpa/supplicant/path" );

std::shared_ptr<DBus::MethodProxy<void,std::map<std::string,DBus::Variant<TYPE_GOES_HERE>>> method_proxy = proxy->create_method<void,std::map<std::string,DBus::Variant<TYPE_GOES_HERE>>( "fi.w1.wpa_supplicant1.Interface.P2PDevice", "GroupAdd" );
```

**Comment by burns97** [comment]
Thanks for the quick and detailed response.  Unfortunately I should have been a bit more descriptive.

The GroupAdd uses the following specification for its collection of variants.

Key | Value type | Description | Required
-- | -- | -- | --
persistent | b | Whether to form a persistent group. | no
persistent_group_object | o |   | no
frequency | i | Operating frequency in MHz | no

In this case each element has a different type.  Based on your additional explanations above, it doesn't sounds like this works in the current version.  I'll take a look at the 2.0 branch and see about giving it a try.

Thanks again!
