### ISSUE TITLE
What's the recommended GLibmm version needed to use dbus-cxx-glib?

### ISSUE THREAD

**Issue by JeysonFlores** [dbus-cxx/dbus-cxx#85]
Hello again, As I said in another issue I'm using Ubuntu 20.04 to run this library. I was using the default Gtkmm stack to build this lib, however it seems Ubuntu 20.04 packs a quite old version of libsigc++ so I built it from source. Everything went Ok however it seems that  I'm using a non-compatible version of GLibmm (GLibmm-2.4), so What's the recommended version of GLibmm?

**Comment by rm5248** [comment]
Unfortunately, I have no idea.  It seems that Debian/ubuntu don't package GTK4 yet, which I believe requires sigc++-3.0.  If you look at the source, you'll notice that the GLib support doesn't actually depend on glibmm at all, instead just using the C interface to interact with glib.  It may not currently be possible to use glib with dbus-cxx at the moment; I am unsure how well mixing versions of libsigc++ works.

I've been considering removing libsigc++ entirely, since most of what it is used for at the moment can be replaced without too much trouble with `std::function` and friends.  I don't particularly want to do that though, as that would break ABI compatibility.

**Comment by JeysonFlores** [comment]
So.... basically in order to use dbus-cxx-glib I've to have installed a GTK4-compatible GLibmm version? Got it then

**Comment by rm5248** [comment]
You have two options:

1. Use the C API for GLib
2. Use an updated version of GLibmm; it seems as though 2.68(at least) uses sigc++-3.0: https://gitlab.gnome.org/GNOME/glibmm/-/blob/7e3dce692704278668042d1dd689d8ed28695b3e/meson.build#L102
