### ISSUE TITLE
Methods that return multiple values

### ISSUE THREAD

**Issue by silverchris** [dbus-cxx/dbus-cxx#95]
Hi All,
I have been playing around with dbus-cxx, and have run into an issue.
I have a method call, that when viewed with dbus-monitor looks like this
method call sender=:1.154 -> dest=com.jci.lds.data serial=1410 path=/com/jci/lds/data; interface=com.jci.lds.data; member=GetPosition
method return sender=:1.63 -> dest=:1.154 reply_serial=1410
   int32 0
   uint64 1600438381
   double 53.7689
   double -2.76504
   int32 17
   double 0
   double 0
   double 99
   double 99

So I tried creating a method in dbus-cxx to call it like this create_method<std::tuple<int32_t,uint64_t,double,double,int32_t,double,double,double,double>()>("GetPosition");

But it is throwing this error DBUS: GetPosition failed Invalid Typecast: MessageIterator:: casting non-numeric type to numeric value

**Comment by rm5248** [comment]
Do you have the introspection XML of that method?  probably the way that the library is parsing it is not the same as is actually being returned from the service that you're connecting to.

Once you have the introspection XML, you should also be able to use dbus-cxx-xml2cpp to auto-generate the code for you instead of making it manually.

**Comment by silverchris** [comment]
The method looks like this. dbus-cxx-xml2cpp Just acts like it would just return a double
```
<method name="GetPosition">
   <annotation name="async_client" value="true" />
   <arg direction="out" name="positionAccuracy" type="i">
      <doc line=" Accuracy = enum(POSITION_UNKNOWN=0x00, POSITION_GPS_3D=0x01, POSITION_GPS_2D=0x02, POSITION_DR=0x03) " />
   </arg>
   <arg direction="out" name="uTCtime" type="t">
      <doc line=" UNIX timestamp from epoch, 0 means invalid." />
   </arg>
   <arg direction="out" name="latitude" type="d">
      <doc line=" Latitude in degrees. " />
   </arg>
   <arg direction="out" name="longitude" type="d">
      <doc line=" Longitude in degrees. " />
   </arg>
   <arg direction="out" name="altitude" type="i">
      <doc line=" Altitude in meters (can be negative). " />
   </arg>
   <arg direction="out" name="heading" type="d">
      <doc line=" Heading value in degrees, clockwise, zero is north. " />
   </arg>
   <arg direction="out" name="velocity" type="d">
      <doc line=" Speed in km/h. " />
   </arg>
   <arg direction="out" name="horizontalAccuracy" type="d">
      <doc line=" Horizontal DOP value. " />
   </arg>
   <arg direction="out" name="verticalAccuracy" type="d">
      <doc line=" Vertical DOP value. " />
   </arg>
   <doc line="GetPosition = This method returns the current position. " />
</method>
```

**Comment by silverchris** [comment]
I should also note that the whole file is here @rm5248 
https://github.com/silverchris/openauto/blob/master/include/Mazda/Dbus/XML/com.jci.lds.data.xml

**Comment by rm5248** [comment]
dbus-cxx does not currently support multiple return values.  I think the error that you're getting is because you're trying to decode the multiple return values as a tuple(DBus struct), so it doesn't let you do that.

If you want to get the multiple return values, I think you'd have to do one of the following:
1. (most generic)Create a new type in the library that handles the multiple return types and send a PR.  The type would look something like `DBus::MultipleReturn<T_arg...>`.  You would then do something like `create_method<DBus::MultipleReturn<int32_t,uint64_t,double,double,int32_t,double,double,double,double>()>("GetPosition");`
2. Create a custom type that handles this.  Unfortunately I don't recall if documentation for this exists at the moment; the best thing you can look at is the [unit test](https://github.com/dbus-cxx/dbus-cxx/blob/acd23b0662827c3543a6ccc26698842c9ffb7a16/unit-tests/custom-type.h) that does this.

Option 2 is really just a special case of option 1, so it really shouldn't be that hard to do.

**Comment by silverchris** [comment]
Thanks for the pointers, let me see what I can do!

**Comment by silverchris** [comment]
Is this roughly what you were thinking of? https://github.com/silverchris/dbus-cxx/commit/70694226590b8cf42b0f5d0cacc97592dda56172

**Comment by rm5248** [comment]
Yes, that's pretty much exactly what I was thinking, although I haven't tested it out yet.

The things to add that I can think of at the moment:

- Update dbus-cxx-xml2cpp to be smart about generating the code from the introspection XML documents.  [This](https://github.com/dbus-cxx/dbus-cxx/blob/acd23b0662827c3543a6ccc26698842c9ffb7a16/tools/code-generator.cpp#L835) is probably the correct spot to modify the code to keep track of multiple return values - perhaps modify the `MethodInfo` class to hold a vector of return values, and then when `returnType()` is called dynamically create the proper signature at that point?  If the vector has 0 entries it returns void, if it has 1 it retunrs that value directly, otherwise it returns a `MethodReturn<typeA,typeB...>` string
- Add a test that sends and receives multiple return values[this can be a little complicated to do, so if you can't figure it out I can do it later].  Check datatests.cpp.
- You may also want to add a line to something like avahi-proxy.cpp(under the tools unit tests) that ensures that the code is generated by xml2cpp correctly.  Something like `DBus::MultipleReturn<int32_t,int32_t,std::string,int32_t,std::string,uint32_t> ret = avahiproxy->ResolveHostName(0, 0, "", 0, 0);`.  This particular test is really just checking to make sure that it compiles, so as long as it compiles it counts that as a passed test.

**Comment by silverchris** [comment]
I do have a bit of a test set up, but haven't cleared the code up enough to call it presentable. 
Will see if I get a bit of time tomorrow to take a look at the rest as well!

**Comment by rm5248** [comment]
Multiple return values now supported; see #101 for PR.
